### PR TITLE
- Adds section for overall model definition layout

### PR DESCRIPTION
**Pull request by sidewaiise**
This should provide an outline for creating a model definition from scratch.

### CODE REVIEW

**Comment by sidewaiise** [comment]
It didnt let me add anyone as a reviewer, hopefully @jeffcressman receives the request.

**Comment by jeffcressman** [comment]
This section is basically the same as the existing Model Definitions section. I'd suggest adding to that section if something is missing, yeah?

**Comment by jeffcressman** [comment]
Maybe have Model.remoteMethod definitions immediately under all of the initial function assignments as you often need to quickly check those to see what a method endpoint (path) is.

**Comment by zbarbuto** [comment]
Model definitions is renamed in a later commit. Was an ambiguous title anyway.

**Pull request merged**
